name: beQuiet Last Seen

on:
  schedule:
    - cron: "0 * * * *"        # hourly (UTC)
    - cron: "58 23 * * *"      # daily summary 23:58 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Hourly update: just scrape & update last_seen when online
      - name: Hourly scrape (MODE=hourly)
        if: ${{ github.event_name == 'schedule' && contains(join(matrix.cron || steps.get_cron.outputs.cron, ' '), '0 * * * *') || github.event_name == 'workflow_dispatch' }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_LASTSEEN }}
          MODE: "hourly"
        run: python bequiet_last_seen.py

      # Daily summary at 23:58 UTC
      - name: Daily summary (MODE=daily)
        if: ${{ github.event_name == 'schedule' && contains(join(matrix.cron || steps.get_cron.outputs.cron, ' '), '58 23 * * *') || github.event_name == 'workflow_dispatch' }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_LASTSEEN }}
          MODE: "daily"
        run: python bequiet_last_seen.py

      - name: Commit state (if changed)
        run: |
          if [ -f state_last_seen.json ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state_last_seen.json || true
            git diff --staged --quiet || git commit -m "Update last-seen state"
            git push
          fi
