name: run

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      MODE: auto
      FORCE_POST: ${{ github.event_name == 'workflow_dispatch' && '1' || '' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show script header
        run: |
          echo "=== bequiet_last_seen.py HEAD ==="
          sed -n '1,140p' bequiet_last_seen.py
          echo "=== grep chunk and flags ==="
          grep -n "post_long_to_discord\|chunk_text\|FORCE_POST" bequiet_last_seen.py || true
          echo "Jetzt in Berlin"
          python - << 'PY'
          from datetime import datetime
          from zoneinfo import ZoneInfo
          print(datetime.now(ZoneInfo("Europe/Berlin")).strftime("%Y-%m-%d %H:%M"))
          PY
          echo "MODE=${MODE} FORCE_POST=${FORCE_POST}"

      - name: Check webhook presence
        run: |
          if [ -z "${DISCORD_WEBHOOK_URL}" ]; then
            echo "Webhook fehlt. Secret DISCORD_WEBHOOK_URL nicht gesetzt."
            exit 1
          else
            echo "::add-mask::${DISCORD_WEBHOOK_URL}"
            echo "Webhook gefunden"
          fi

      - name: Run script
        run: python bequiet_last_seen.py

      - name: Commit state
        if: ${{ hashFiles('state_last_seen.json') != '' }}
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add state_last_seen.json || true
          git commit -m "Update last-seen state" || echo "nothing to commit"
          git push
