name: run

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      MODE: auto
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show script header
        run: |
          echo "=== bequiet_last_seen.py HEAD ==="
          sed -n '1,80p' bequiet_last_seen.py
          echo "=== grep chunk signatures ==="
          grep -n "post_long_to_discord\|chunk_text" bequiet_last_seen.py || true

      - name: Run script
        run: python bequiet_last_seen.py

      - name: Commit state
        if: ${{ hashFiles('state_last_seen.json') != '' }}
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add state_last_seen.json || true
          git commit -m "Update last-seen state" || echo "nothing to commit"
          git push
