name: beQuiet last seen

on:
  schedule:
    - cron: "0 * * * *"        # stündlich (UTC)
  workflow_dispatch:            # manueller Test-Run

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
      # hier binden wir DEIN Secret ein:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_LASTSEEN }}
      MODE: auto
      # Bei manuellem Run sofort posten:
      FORCE_POST: ${{ github.event_name == 'workflow_dispatch' && '1' || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Show Berlin time & mode
        run: |
          python - << 'PY'
          from datetime import datetime
          import os, zoneinfo
          tz = zoneinfo.ZoneInfo("Europe/Berlin")
          print("Jetzt in Berlin:", datetime.now(tz).strftime("%Y-%m-%d %H:%M"))
          print("MODE =", os.getenv("MODE"))
          print("FORCE_POST =", os.getenv("FORCE_POST"))
          PY

      - name: Check webhook presence (no leak)
        run: |
          if [ -n "${DISCORD_WEBHOOK_URL}" ]; then
            echo "DISCORD_WEBHOOK_URL: SET"
          else
            echo "DISCORD_WEBHOOK_URL: MISSING"
            exit 1
          fi

      - name: Run tracker
        run: python bequiet_last_seen.py
